version: '3.8'

services:
  api-bingo:
    container_name: api-bingo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    environment:
      - ASPNETCORE_URLS=http://+:2000
